// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CalcComp,hls_ip_2016_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=8.159000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=66,HLS_SYN_LUT=252}" *)

module CalcComp (
        data,
        ap_return
);

parameter    ap_const_lv32_3E19999A = 32'b111110000110011001100110011010;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv23_0 = 23'b00000000000000000000000;
parameter    ap_const_lv5_3 = 5'b11;

input  [31:0] data;
output  [7:0] ap_return;

wire   [31:0] data_to_int_fu_50_p1;
wire   [7:0] tmp_fu_54_p4;
wire   [22:0] tmp_1_fu_64_p1;
wire   [0:0] notrhs_fu_74_p2;
wire   [0:0] notlhs_fu_68_p2;
wire   [0:0] tmp_2_fu_80_p2;
wire   [0:0] tmp_3_fu_44_p2;
wire   [0:0] tmp_4_fu_86_p2;

CalcComp_fcmp_32nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
CalcComp_fcmp_32nbkb_U1(
    .din0(data),
    .din1(ap_const_lv32_3E19999A),
    .opcode(ap_const_lv5_3),
    .dout(tmp_3_fu_44_p2)
);

assign ap_return = tmp_4_fu_86_p2;

assign data_to_int_fu_50_p1 = data;

assign notlhs_fu_68_p2 = ((tmp_fu_54_p4 != ap_const_lv8_FF) ? 1'b1 : 1'b0);

assign notrhs_fu_74_p2 = ((tmp_1_fu_64_p1 == ap_const_lv23_0) ? 1'b1 : 1'b0);

assign tmp_1_fu_64_p1 = data_to_int_fu_50_p1[22:0];

assign tmp_2_fu_80_p2 = (notrhs_fu_74_p2 | notlhs_fu_68_p2);

assign tmp_4_fu_86_p2 = (tmp_2_fu_80_p2 & tmp_3_fu_44_p2);

assign tmp_fu_54_p4 = {{data_to_int_fu_50_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

endmodule //CalcComp
