# TCL File Generated by Component Editor 15.1
# Sat Dec 05 10:05:33 JST 2015
# DO NOT MODIFY


# 
# aq_split "aq_split" v1.0
#  2015.12.05.10:05:33
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module aq_split
# 
set_module_property DESCRIPTION ""
set_module_property NAME aq_split
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aq_split
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aq_split
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aq_split.v VERILOG PATH src/aq_split.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point din
# 
add_interface din conduit end
set_interface_property din associatedClock clock
set_interface_property din associatedReset ""
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din din enable Input 1


# 
# connection point dout1
# 
add_interface dout1 conduit end
set_interface_property dout1 associatedClock clock
set_interface_property dout1 associatedReset ""
set_interface_property dout1 ENABLED true
set_interface_property dout1 EXPORT_OF ""
set_interface_property dout1 PORT_NAME_MAP ""
set_interface_property dout1 CMSIS_SVD_VARIABLES ""
set_interface_property dout1 SVD_ADDRESS_GROUP ""

add_interface_port dout1 dout1 enable Output 1


# 
# connection point dout2
# 
add_interface dout2 conduit end
set_interface_property dout2 associatedClock clock
set_interface_property dout2 associatedReset ""
set_interface_property dout2 ENABLED true
set_interface_property dout2 EXPORT_OF ""
set_interface_property dout2 PORT_NAME_MAP ""
set_interface_property dout2 CMSIS_SVD_VARIABLES ""
set_interface_property dout2 SVD_ADDRESS_GROUP ""

add_interface_port dout2 dout2 enable Output 1

