// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CalcGrad,hls_ip_2016_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.800000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=34,HLS_SYN_LUT=68}" *)

module CalcGrad (
        ap_clk,
        ap_rst,
        x,
        y,
        atan2_table_Addr_A,
        atan2_table_EN_A,
        atan2_table_WEN_A,
        atan2_table_Din_A,
        atan2_table_Dout_A,
        atan2_table_Clk_A,
        atan2_table_Rst_A,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv8_8 = 8'b1000;

input   ap_clk;
input   ap_rst;
input  [15:0] x;
input  [15:0] y;
output  [31:0] atan2_table_Addr_A;
output   atan2_table_EN_A;
output  [0:0] atan2_table_WEN_A;
output  [7:0] atan2_table_Din_A;
input  [7:0] atan2_table_Dout_A;
output   atan2_table_Clk_A;
output   atan2_table_Rst_A;
output  [7:0] ap_return;

reg atan2_table_EN_A;

reg   [15:0] y_read_reg_157;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg   [15:0] x_read_reg_162;
reg    ap_enable_reg_pp0_iter1;
wire   [63:0] tmp_s_fu_126_p1;
wire   [31:0] atan2_table_Addr_A_orig;
wire   [7:0] tmp_4_fu_74_p1;
wire   [0:0] tmp_1_fu_66_p3;
wire   [7:0] tmp_2_fu_78_p2;
wire   [7:0] tmp_6_fu_100_p1;
wire   [0:0] tmp_5_fu_92_p3;
wire   [7:0] tmp_7_fu_104_p2;
wire   [7:0] k_fu_110_p3;
wire   [7:0] j_fu_84_p3;
wire   [15:0] tmp_3_fu_118_p3;
wire   [15:0] x_lobit1_fu_131_p2;
wire   [0:0] tmp_fu_135_p3;
wire   [7:0] tmp_8_fu_143_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_pipeline_idle_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'b1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
        x_read_reg_162 <= x;
        y_read_reg_157 <= y;
    end
end

assign ap_pipeline_idle_pp0 = 1'b0;

always @ (*) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & 1'b1)) begin
        atan2_table_EN_A = 1'b1;
    end else begin
        atan2_table_EN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_0];

assign ap_return = ((tmp_fu_135_p3[0:0] === 1'b1) ? tmp_8_fu_143_p2 : atan2_table_Dout_A);

assign atan2_table_Addr_A = atan2_table_Addr_A_orig << ap_const_lv32_0;

assign atan2_table_Addr_A_orig = tmp_s_fu_126_p1;

assign atan2_table_Clk_A = ap_clk;

assign atan2_table_Din_A = ap_const_lv8_0;

assign atan2_table_Rst_A = ap_rst;

assign atan2_table_WEN_A = 1'b0;

assign j_fu_84_p3 = ((tmp_1_fu_66_p3[0:0] === 1'b1) ? tmp_2_fu_78_p2 : tmp_4_fu_74_p1);

assign k_fu_110_p3 = ((tmp_5_fu_92_p3[0:0] === 1'b1) ? tmp_7_fu_104_p2 : tmp_6_fu_100_p1);

assign tmp_1_fu_66_p3 = x[ap_const_lv32_F];

assign tmp_2_fu_78_p2 = (ap_const_lv8_0 - tmp_4_fu_74_p1);

assign tmp_3_fu_118_p3 = {{k_fu_110_p3}, {j_fu_84_p3}};

assign tmp_4_fu_74_p1 = x[7:0];

assign tmp_5_fu_92_p3 = y[ap_const_lv32_F];

assign tmp_6_fu_100_p1 = y[7:0];

assign tmp_7_fu_104_p2 = (ap_const_lv8_0 - tmp_6_fu_100_p1);

assign tmp_8_fu_143_p2 = (ap_const_lv8_8 - atan2_table_Dout_A);

assign tmp_fu_135_p3 = x_lobit1_fu_131_p2[ap_const_lv32_F];

assign tmp_s_fu_126_p1 = tmp_3_fu_118_p3;

assign x_lobit1_fu_131_p2 = (y_read_reg_157 ^ x_read_reg_162);

endmodule //CalcGrad
