# TCL File Generated by Component Editor 15.1
# Wed Dec 09 23:27:16 JST 2015
# DO NOT MODIFY


# 
# aq_intreg "aq_intreg" v1.0
#  2015.12.09.23:27:16
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module aq_intreg
# 
set_module_property DESCRIPTION ""
set_module_property NAME aq_intreg
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aq_intreg
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aq_intreg
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aq_intreg.v VERILOG PATH src/aq_intreg.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clk_in
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""

add_interface_port rst_n RST_N reset_n Input 1


# 
# connection point int
# 
add_interface int conduit end
set_interface_property int associatedClock ""
set_interface_property int associatedReset ""
set_interface_property int ENABLED true
set_interface_property int EXPORT_OF ""
set_interface_property int PORT_NAME_MAP ""
set_interface_property int CMSIS_SVD_VARIABLES ""
set_interface_property int SVD_ADDRESS_GROUP ""

add_interface_port int INT data Output 1


# 
# connection point din
# 
add_interface din conduit end
set_interface_property din associatedClock ""
set_interface_property din associatedReset ""
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din DIN data Input 1


# 
# connection point clk_out
# 
add_interface clk_out clock end
set_interface_property clk_out clockRate 0
set_interface_property clk_out ENABLED true
set_interface_property clk_out EXPORT_OF ""
set_interface_property clk_out PORT_NAME_MAP ""
set_interface_property clk_out CMSIS_SVD_VARIABLES ""
set_interface_property clk_out SVD_ADDRESS_GROUP ""

add_interface_port clk_out CLKB clk Input 1


# 
# connection point clk_in
# 
add_interface clk_in clock end
set_interface_property clk_in clockRate 0
set_interface_property clk_in ENABLED true
set_interface_property clk_in EXPORT_OF ""
set_interface_property clk_in PORT_NAME_MAP ""
set_interface_property clk_in CMSIS_SVD_VARIABLES ""
set_interface_property clk_in SVD_ADDRESS_GROUP ""

add_interface_port clk_in CLKA clk Input 1

