# TCL File Generated by Component Editor 15.1
# Sat Dec 05 09:48:45 JST 2015
# DO NOT MODIFY


# 
# aq_fifosplit32_w "aq_fifosplit32_w" v1.0
#  2015.12.05.09:48:45
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module aq_fifosplit32_w
# 
set_module_property DESCRIPTION ""
set_module_property NAME aq_fifosplit32_w
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aq_fifosplit32_w
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aq_fifosplit32_w
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aq_fifosplit32_w.v VERILOG PATH src/aq_fifosplit32_w.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point re
# 
add_interface re conduit end
set_interface_property re associatedClock clock
set_interface_property re associatedReset ""
set_interface_property re ENABLED true
set_interface_property re EXPORT_OF ""
set_interface_property re PORT_NAME_MAP ""
set_interface_property re CMSIS_SVD_VARIABLES ""
set_interface_property re SVD_ADDRESS_GROUP ""

add_interface_port re WR_OUT_RE enable Input 1


# 
# connection point empty
# 
add_interface empty conduit end
set_interface_property empty associatedClock clock
set_interface_property empty associatedReset ""
set_interface_property empty ENABLED true
set_interface_property empty EXPORT_OF ""
set_interface_property empty PORT_NAME_MAP ""
set_interface_property empty CMSIS_SVD_VARIABLES ""
set_interface_property empty SVD_ADDRESS_GROUP ""

add_interface_port empty WR_OUT_EMPTY empty Output 1


# 
# connection point do
# 
add_interface do conduit end
set_interface_property do associatedClock clock
set_interface_property do associatedReset ""
set_interface_property do ENABLED true
set_interface_property do EXPORT_OF ""
set_interface_property do PORT_NAME_MAP ""
set_interface_property do CMSIS_SVD_VARIABLES ""
set_interface_property do SVD_ADDRESS_GROUP ""

add_interface_port do WR_OUT_DO data Output 32


# 
# connection point fifo
# 
add_interface fifo conduit end
set_interface_property fifo associatedClock clock
set_interface_property fifo associatedReset ""
set_interface_property fifo ENABLED true
set_interface_property fifo EXPORT_OF ""
set_interface_property fifo PORT_NAME_MAP ""
set_interface_property fifo CMSIS_SVD_VARIABLES ""
set_interface_property fifo SVD_ADDRESS_GROUP ""

add_interface_port fifo WR_IN_DATA data Input 32
add_interface_port fifo WR_IN_EMPTY empty Input 1
add_interface_port fifo WR_IN_RE enable Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1

