# TCL File Generated by Component Editor 15.1
# Thu Dec 03 13:18:38 JST 2015
# DO NOT MODIFY


# 
# aq_axi_lite_slave "aq_axi_lite_slave" v1.0
#  2015.12.03.13:18:38
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module aq_axi_lite_slave
# 
set_module_property DESCRIPTION ""
set_module_property NAME aq_axi_lite_slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aq_axi_lite_slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aq_axi_lite_slave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aq_axi_lite_slave.v VERILOG PATH src/aq_axi_lite_slave.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point debug
# 
add_interface debug conduit end
set_interface_property debug associatedClock axi_clk
set_interface_property debug associatedReset ""
set_interface_property debug ENABLED true
set_interface_property debug EXPORT_OF ""
set_interface_property debug PORT_NAME_MAP ""
set_interface_property debug CMSIS_SVD_VARIABLES ""
set_interface_property debug SVD_ADDRESS_GROUP ""

add_interface_port debug DEBUG debug Output 32


# 
# connection point aresetn
# 
add_interface aresetn reset end
set_interface_property aresetn associatedClock axi_clk
set_interface_property aresetn synchronousEdges DEASSERT
set_interface_property aresetn ENABLED true
set_interface_property aresetn EXPORT_OF ""
set_interface_property aresetn PORT_NAME_MAP ""
set_interface_property aresetn CMSIS_SVD_VARIABLES ""
set_interface_property aresetn SVD_ADDRESS_GROUP ""

add_interface_port aresetn ARESETN reset_n Input 1


# 
# connection point axi_clk
# 
add_interface axi_clk clock end
set_interface_property axi_clk clockRate 0
set_interface_property axi_clk ENABLED true
set_interface_property axi_clk EXPORT_OF ""
set_interface_property axi_clk PORT_NAME_MAP ""
set_interface_property axi_clk CMSIS_SVD_VARIABLES ""
set_interface_property axi_clk SVD_ADDRESS_GROUP ""

add_interface_port axi_clk ACLK clk Input 1


# 
# connection point local_bus
# 
add_interface local_bus conduit end
set_interface_property local_bus associatedClock axi_clk
set_interface_property local_bus associatedReset ""
set_interface_property local_bus ENABLED true
set_interface_property local_bus EXPORT_OF ""
set_interface_property local_bus PORT_NAME_MAP ""
set_interface_property local_bus CMSIS_SVD_VARIABLES ""
set_interface_property local_bus SVD_ADDRESS_GROUP ""

add_interface_port local_bus LOCAL_ACK ack Input 1
add_interface_port local_bus LOCAL_ADDR addr Output 32
add_interface_port local_bus LOCAL_BE be Output 4
add_interface_port local_bus LOCAL_CS cs Output 1
add_interface_port local_bus LOCAL_RDATA rdata Input 32
add_interface_port local_bus LOCAL_RNW rnw Output 1
add_interface_port local_bus LOCAL_WDATA wdata Output 32


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock axi_clk
set_interface_property altera_axi4lite_slave associatedReset aresetn
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave S_AXI_AWADDR awaddr Input 16
add_interface_port altera_axi4lite_slave S_AXI_AWPROT awprot Input 3
add_interface_port altera_axi4lite_slave S_AXI_AWVALID awvalid Input 1
add_interface_port altera_axi4lite_slave S_AXI_AWREADY awready Output 1
add_interface_port altera_axi4lite_slave S_AXI_WDATA wdata Input 32
add_interface_port altera_axi4lite_slave S_AXI_WSTRB wstrb Input 4
add_interface_port altera_axi4lite_slave S_AXI_WVALID wvalid Input 1
add_interface_port altera_axi4lite_slave S_AXI_WREADY wready Output 1
add_interface_port altera_axi4lite_slave S_AXI_BVALID bvalid Output 1
add_interface_port altera_axi4lite_slave S_AXI_BREADY bready Input 1
add_interface_port altera_axi4lite_slave S_AXI_BRESP bresp Output 2
add_interface_port altera_axi4lite_slave S_AXI_ARADDR araddr Input 16
add_interface_port altera_axi4lite_slave S_AXI_ARPROT arprot Input 3
add_interface_port altera_axi4lite_slave S_AXI_ARVALID arvalid Input 1
add_interface_port altera_axi4lite_slave S_AXI_ARREADY arready Output 1
add_interface_port altera_axi4lite_slave S_AXI_RDATA rdata Output 32
add_interface_port altera_axi4lite_slave S_AXI_RRESP rresp Output 2
add_interface_port altera_axi4lite_slave S_AXI_RVALID rvalid Output 1
add_interface_port altera_axi4lite_slave S_AXI_RREADY rready Input 1


# 
# connection point axi_other
# 
add_interface axi_other conduit end
set_interface_property axi_other associatedClock axi_clk
set_interface_property axi_other associatedReset ""
set_interface_property axi_other ENABLED true
set_interface_property axi_other EXPORT_OF ""
set_interface_property axi_other PORT_NAME_MAP ""
set_interface_property axi_other CMSIS_SVD_VARIABLES ""
set_interface_property axi_other SVD_ADDRESS_GROUP ""

add_interface_port axi_other S_AXI_ARCACHE arcache Input 4
add_interface_port axi_other S_AXI_AWCACHE awcache Input 4

