// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CalcSumMag,hls_ip_2016_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=43,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=43,HLS_SYN_FF=3663,HLS_SYN_LUT=6265}" *)

module CalcSumMag (
        ap_clk,
        ap_rst,
        l00,
        l01,
        l02,
        l10,
        l11,
        l12,
        l20,
        l21,
        l22,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] l00;
input  [31:0] l01;
input  [31:0] l02;
input  [31:0] l10;
input  [31:0] l11;
input  [31:0] l12;
input  [31:0] l20;
input  [31:0] l21;
input  [31:0] l22;
output  [31:0] ap_return;

reg   [31:0] l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter5_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter6_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter7_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter8_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter9_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter10_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter11_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter12_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter13_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter14_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter15_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter16_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter17_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter18_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter19_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter20_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter21_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter22_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter23_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter24_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter25_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter26_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter27_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter28_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter29_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter30_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter31_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter32_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter33_l22_read_reg_168;
reg   [31:0] ap_pipeline_reg_pp0_iter34_l22_read_reg_168;
reg   [31:0] l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter5_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter6_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter7_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter8_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter9_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter10_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter11_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter12_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter13_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter14_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter15_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter16_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter17_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter18_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter19_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter20_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter21_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter22_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter23_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter24_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter25_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter26_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter27_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter28_l21_read_reg_174;
reg   [31:0] ap_pipeline_reg_pp0_iter29_l21_read_reg_174;
reg   [31:0] l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter5_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter6_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter7_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter8_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter9_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter10_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter11_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter12_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter13_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter14_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter15_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter16_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter17_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter18_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter19_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter20_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter21_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter22_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter23_l20_read_reg_180;
reg   [31:0] ap_pipeline_reg_pp0_iter24_l20_read_reg_180;
reg   [31:0] l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter5_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter6_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter7_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter8_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter9_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter10_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter11_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter12_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter13_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter14_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter15_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter16_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter17_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter18_l12_read_reg_186;
reg   [31:0] ap_pipeline_reg_pp0_iter19_l12_read_reg_186;
reg   [31:0] l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter5_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter6_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter7_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter8_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter9_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter10_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter11_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter12_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter13_l11_read_reg_192;
reg   [31:0] ap_pipeline_reg_pp0_iter14_l11_read_reg_192;
reg   [31:0] l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter5_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter6_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter7_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter8_l10_read_reg_198;
reg   [31:0] ap_pipeline_reg_pp0_iter9_l10_read_reg_198;
reg   [31:0] l02_read_reg_204;
reg   [31:0] ap_pipeline_reg_pp0_iter1_l02_read_reg_204;
reg   [31:0] ap_pipeline_reg_pp0_iter2_l02_read_reg_204;
reg   [31:0] ap_pipeline_reg_pp0_iter3_l02_read_reg_204;
reg   [31:0] ap_pipeline_reg_pp0_iter4_l02_read_reg_204;
wire   [31:0] grp_fu_128_p2;
reg   [31:0] tmp_reg_222;
wire   [31:0] grp_fu_134_p2;
reg   [31:0] tmp_1_reg_227;
wire   [31:0] grp_fu_96_p2;
reg   [31:0] tmp_2_reg_232;
wire   [31:0] grp_fu_140_p2;
reg   [31:0] tmp_3_reg_237;
wire   [31:0] grp_fu_100_p2;
reg   [31:0] tmp_4_reg_242;
wire   [31:0] grp_fu_144_p2;
reg   [31:0] tmp_5_reg_247;
wire   [31:0] grp_fu_104_p2;
reg   [31:0] tmp_6_reg_252;
wire   [31:0] grp_fu_148_p2;
reg   [31:0] tmp_7_reg_257;
wire   [31:0] grp_fu_108_p2;
reg   [31:0] tmp_8_reg_262;
wire   [31:0] grp_fu_152_p2;
reg   [31:0] tmp_9_reg_267;
wire   [31:0] grp_fu_112_p2;
reg   [31:0] tmp_s_reg_272;
wire   [31:0] grp_fu_156_p2;
reg   [31:0] tmp_10_reg_277;
wire   [31:0] grp_fu_116_p2;
reg   [31:0] tmp_11_reg_282;
wire   [31:0] grp_fu_160_p2;
reg   [31:0] tmp_12_reg_287;
wire   [31:0] grp_fu_120_p2;
reg   [31:0] tmp_13_reg_292;
wire   [31:0] grp_fu_164_p2;
reg   [31:0] tmp_14_reg_297;
wire   [31:0] grp_fu_124_p2;

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_222),
    .din1(tmp_1_reg_227),
    .ce(1'b1),
    .dout(grp_fu_96_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_reg_232),
    .din1(tmp_3_reg_237),
    .ce(1'b1),
    .dout(grp_fu_100_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_242),
    .din1(tmp_5_reg_247),
    .ce(1'b1),
    .dout(grp_fu_104_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_6_reg_252),
    .din1(tmp_7_reg_257),
    .ce(1'b1),
    .dout(grp_fu_108_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_8_reg_262),
    .din1(tmp_9_reg_267),
    .ce(1'b1),
    .dout(grp_fu_112_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_reg_272),
    .din1(tmp_10_reg_277),
    .ce(1'b1),
    .dout(grp_fu_116_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_11_reg_282),
    .din1(tmp_12_reg_287),
    .ce(1'b1),
    .dout(grp_fu_120_p2)
);

CalcSumMag_fadd_3bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fadd_3bkb_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_13_reg_292),
    .din1(tmp_14_reg_297),
    .ce(1'b1),
    .dout(grp_fu_124_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(l00),
    .din1(l00),
    .ce(1'b1),
    .dout(grp_fu_128_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(l01),
    .din1(l01),
    .ce(1'b1),
    .dout(grp_fu_134_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter4_l02_read_reg_204),
    .din1(ap_pipeline_reg_pp0_iter4_l02_read_reg_204),
    .ce(1'b1),
    .dout(grp_fu_140_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter9_l10_read_reg_198),
    .din1(ap_pipeline_reg_pp0_iter9_l10_read_reg_198),
    .ce(1'b1),
    .dout(grp_fu_144_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter14_l11_read_reg_192),
    .din1(ap_pipeline_reg_pp0_iter14_l11_read_reg_192),
    .ce(1'b1),
    .dout(grp_fu_148_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter19_l12_read_reg_186),
    .din1(ap_pipeline_reg_pp0_iter19_l12_read_reg_186),
    .ce(1'b1),
    .dout(grp_fu_152_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter24_l20_read_reg_180),
    .din1(ap_pipeline_reg_pp0_iter24_l20_read_reg_180),
    .ce(1'b1),
    .dout(grp_fu_156_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter29_l21_read_reg_174),
    .din1(ap_pipeline_reg_pp0_iter29_l21_read_reg_174),
    .ce(1'b1),
    .dout(grp_fu_160_p2)
);

CalcSumMag_fmul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
CalcSumMag_fmul_3cud_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_pipeline_reg_pp0_iter34_l22_read_reg_168),
    .din1(ap_pipeline_reg_pp0_iter34_l22_read_reg_168),
    .ce(1'b1),
    .dout(grp_fu_164_p2)
);

always @ (posedge ap_clk) begin
    if ((1'b1 == 1'b1)) begin
        ap_pipeline_reg_pp0_iter10_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter9_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter10_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter9_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter10_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter9_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter10_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter9_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter10_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter9_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter11_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter10_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter11_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter10_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter11_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter10_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter11_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter10_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter11_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter10_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter12_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter11_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter12_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter11_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter12_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter11_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter12_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter11_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter12_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter11_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter13_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter12_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter13_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter12_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter13_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter12_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter13_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter12_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter13_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter12_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter14_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter13_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter14_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter13_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter14_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter13_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter14_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter13_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter14_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter13_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter15_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter14_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter15_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter14_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter15_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter14_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter15_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter14_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter16_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter15_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter16_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter15_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter16_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter15_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter16_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter15_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter17_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter16_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter17_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter16_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter17_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter16_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter17_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter16_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter18_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter17_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter18_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter17_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter18_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter17_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter18_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter17_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter19_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter18_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter19_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter18_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter19_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter18_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter19_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter18_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter1_l02_read_reg_204 <= l02_read_reg_204;
        ap_pipeline_reg_pp0_iter1_l10_read_reg_198 <= l10_read_reg_198;
        ap_pipeline_reg_pp0_iter1_l11_read_reg_192 <= l11_read_reg_192;
        ap_pipeline_reg_pp0_iter1_l12_read_reg_186 <= l12_read_reg_186;
        ap_pipeline_reg_pp0_iter1_l20_read_reg_180 <= l20_read_reg_180;
        ap_pipeline_reg_pp0_iter1_l21_read_reg_174 <= l21_read_reg_174;
        ap_pipeline_reg_pp0_iter1_l22_read_reg_168 <= l22_read_reg_168;
        ap_pipeline_reg_pp0_iter20_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter19_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter20_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter19_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter20_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter19_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter21_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter20_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter21_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter20_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter21_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter20_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter22_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter21_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter22_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter21_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter22_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter21_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter23_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter22_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter23_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter22_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter23_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter22_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter24_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter23_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter24_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter23_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter24_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter23_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter25_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter24_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter25_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter24_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter26_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter25_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter26_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter25_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter27_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter26_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter27_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter26_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter28_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter27_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter28_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter27_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter29_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter28_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter29_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter28_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter2_l02_read_reg_204 <= ap_pipeline_reg_pp0_iter1_l02_read_reg_204;
        ap_pipeline_reg_pp0_iter2_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter1_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter2_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter1_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter2_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter1_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter2_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter1_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter2_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter1_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter2_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter1_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter30_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter29_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter31_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter30_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter32_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter31_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter33_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter32_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter34_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter33_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter3_l02_read_reg_204 <= ap_pipeline_reg_pp0_iter2_l02_read_reg_204;
        ap_pipeline_reg_pp0_iter3_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter2_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter3_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter2_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter3_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter2_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter3_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter2_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter3_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter2_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter3_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter2_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter4_l02_read_reg_204 <= ap_pipeline_reg_pp0_iter3_l02_read_reg_204;
        ap_pipeline_reg_pp0_iter4_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter3_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter4_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter3_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter4_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter3_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter4_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter3_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter4_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter3_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter4_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter3_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter5_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter4_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter5_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter4_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter5_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter4_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter5_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter4_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter5_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter4_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter5_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter4_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter6_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter5_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter6_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter5_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter6_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter5_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter6_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter5_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter6_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter5_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter6_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter5_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter7_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter6_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter7_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter6_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter7_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter6_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter7_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter6_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter7_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter6_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter7_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter6_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter8_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter7_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter8_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter7_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter8_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter7_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter8_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter7_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter8_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter7_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter8_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter7_l22_read_reg_168;
        ap_pipeline_reg_pp0_iter9_l10_read_reg_198 <= ap_pipeline_reg_pp0_iter8_l10_read_reg_198;
        ap_pipeline_reg_pp0_iter9_l11_read_reg_192 <= ap_pipeline_reg_pp0_iter8_l11_read_reg_192;
        ap_pipeline_reg_pp0_iter9_l12_read_reg_186 <= ap_pipeline_reg_pp0_iter8_l12_read_reg_186;
        ap_pipeline_reg_pp0_iter9_l20_read_reg_180 <= ap_pipeline_reg_pp0_iter8_l20_read_reg_180;
        ap_pipeline_reg_pp0_iter9_l21_read_reg_174 <= ap_pipeline_reg_pp0_iter8_l21_read_reg_174;
        ap_pipeline_reg_pp0_iter9_l22_read_reg_168 <= ap_pipeline_reg_pp0_iter8_l22_read_reg_168;
        l02_read_reg_204 <= l02;
        l10_read_reg_198 <= l10;
        l11_read_reg_192 <= l11;
        l12_read_reg_186 <= l12;
        l20_read_reg_180 <= l20;
        l21_read_reg_174 <= l21;
        l22_read_reg_168 <= l22;
        tmp_10_reg_277 <= grp_fu_156_p2;
        tmp_11_reg_282 <= grp_fu_116_p2;
        tmp_12_reg_287 <= grp_fu_160_p2;
        tmp_13_reg_292 <= grp_fu_120_p2;
        tmp_14_reg_297 <= grp_fu_164_p2;
        tmp_1_reg_227 <= grp_fu_134_p2;
        tmp_2_reg_232 <= grp_fu_96_p2;
        tmp_3_reg_237 <= grp_fu_140_p2;
        tmp_4_reg_242 <= grp_fu_100_p2;
        tmp_5_reg_247 <= grp_fu_144_p2;
        tmp_6_reg_252 <= grp_fu_104_p2;
        tmp_7_reg_257 <= grp_fu_148_p2;
        tmp_8_reg_262 <= grp_fu_108_p2;
        tmp_9_reg_267 <= grp_fu_152_p2;
        tmp_reg_222 <= grp_fu_128_p2;
        tmp_s_reg_272 <= grp_fu_112_p2;
    end
end

assign ap_return = grp_fu_124_p2;

endmodule //CalcSumMag
