# TCL File Generated by Component Editor 15.1
# Sat Dec 05 11:22:07 JST 2015
# DO NOT MODIFY


# 
# aq_vga "aq_vga" v1.0
#  2015.12.05.11:22:07
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module aq_vga
# 
set_module_property DESCRIPTION ""
set_module_property NAME aq_vga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aq_vga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL aq_vga
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file aq_vga.v VERILOG PATH src/aq_vga.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock ""
set_interface_property reset_sink synchronousEdges NONE
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RST_N reset_n Input 1


# 
# connection point din
# 
add_interface din conduit end
set_interface_property din associatedClock clock
set_interface_property din associatedReset ""
set_interface_property din ENABLED true
set_interface_property din EXPORT_OF ""
set_interface_property din PORT_NAME_MAP ""
set_interface_property din CMSIS_SVD_VARIABLES ""
set_interface_property din SVD_ADDRESS_GROUP ""

add_interface_port din DIN data Input 32


# 
# connection point active
# 
add_interface active conduit end
set_interface_property active associatedClock clock
set_interface_property active associatedReset ""
set_interface_property active ENABLED true
set_interface_property active EXPORT_OF ""
set_interface_property active PORT_NAME_MAP ""
set_interface_property active CMSIS_SVD_VARIABLES ""
set_interface_property active SVD_ADDRESS_GROUP ""

add_interface_port active ACTIVE enable Input 1


# 
# connection point vga_out
# 
add_interface vga_out conduit end
set_interface_property vga_out associatedClock ""
set_interface_property vga_out associatedReset ""
set_interface_property vga_out ENABLED true
set_interface_property vga_out EXPORT_OF ""
set_interface_property vga_out PORT_NAME_MAP ""
set_interface_property vga_out CMSIS_SVD_VARIABLES ""
set_interface_property vga_out SVD_ADDRESS_GROUP ""

add_interface_port vga_out DOUT_B b Output 8
add_interface_port vga_out DOUT_G g Output 8
add_interface_port vga_out DOUT_R r Output 8
add_interface_port vga_out HSYNC hsync Output 1
add_interface_port vga_out VSYNC vsync Output 1


# 
# connection point vsync
# 
add_interface vsync conduit end
set_interface_property vsync associatedClock ""
set_interface_property vsync associatedReset ""
set_interface_property vsync ENABLED true
set_interface_property vsync EXPORT_OF ""
set_interface_property vsync PORT_NAME_MAP ""
set_interface_property vsync CMSIS_SVD_VARIABLES ""
set_interface_property vsync SVD_ADDRESS_GROUP ""

add_interface_port vsync VIN vsync Input 1


# 
# connection point hsync
# 
add_interface hsync conduit end
set_interface_property hsync associatedClock ""
set_interface_property hsync associatedReset ""
set_interface_property hsync ENABLED true
set_interface_property hsync EXPORT_OF ""
set_interface_property hsync PORT_NAME_MAP ""
set_interface_property hsync CMSIS_SVD_VARIABLES ""
set_interface_property hsync SVD_ADDRESS_GROUP ""

add_interface_port hsync HIN hsync Input 1

